VadimCpp/events4friends.ru-react

src/AppRouter.js
src/components/EventItem.js
src/index.css
src/views/ArchiveView.js
src/views/EventView.js
src/views/MainView.js

Hi, these fixes make it possible to watch past events.
+ A new section called archive has been added.
Accept the changes, if everything is fine with them =)

Fix display events that has already passed

---

src/views/EventView/index.js

Пофиксил отображение организатора мероприятия. Баг внесен смерженным PR https://github.com/VadimCpp/events4friends.ru-react/pull/209

#199 fix display event author name

---

.eslintrc
package.json
src/App.js
src/components/Button/Button.css
src/components/Button/index.js
src/components/ButtonExternalLink/index.js
src/components/ButtonLink/index.js
src/components/EventForm/helper.js
src/components/ScrollToTop/index.js
src/provider/clipboard.js
src/provider/firebase.js
src/provider/telegram.js
src/views/CommunitiesView/CommunitiesView.css
src/views/CommunitiesView/index.js
src/views/EditEventView/index.js
src/views/EventView/EventView.css
src/views/EventView/index.js
src/views/EventsView/EventsView.css
src/views/EventsView/index.js
src/views/ProfileView/index.js

Предлагаю в дальнейшем максимально выносить оформление в стили, исходя из этого конструировать компоненты, т.е. по возможности избегать использования `style={{}}`, это улучшит читаемость и поддержку.
Добавил пакет classnames для работы с классами. https://www.npmjs.com/package/classnames

#199 вынес некоторые стили в css, изменен App.js, методы работы с базой вынесены в provider.

---

src/views/WelcomeView/index.js

изменения по задаче номер #226

#226 change title on main page

---

src/App.js
src/context/AuthContext.js
src/context/DataContext.js
src/hooks/useAuth.js
src/hooks/useData.js
src/views/EventView/index.js
src/views/EventsView/index.js
src/views/ServiceView/index.js
src/views/ServicesView/index.js

В рамках тикета добавлены - флаг подключения к базе данных и флаги загрузки мероприятий и услуг.

Индикатор подключения к базе данных

---

src/App.js
src/components/EventCard/index.js
src/components/ServiceCard/index.js
src/views/EventView/index.js

Поправлен баг с warning (см. тикет https://github.com/VadimCpp/events4friends.ru-react/issues/252)
Удалил неиспользуемый импорт momentjs. Локаль теперь импортируется один раз в App.js

Убрать warning от библиотеки moment

---

src/components/SocialNetworkLink/SocialNetworkLink.css

used #fc5200 off color from off. web page strava
используется #fc5200 официальный цвет взятый из веб страницы strava

#303 add border color in link strava

---

src/components/EventCard/index.js
src/views/EventsView/index.js

rename const in components EventsView and EventCard

#309 Refactor:  rename notice to NOTICES

---

src/hooks/useData.js

removed second params afterSuccess
refactor func changed events and Services

#310 Refactor: remove second param to func

---

src/components/Button/index.js
src/views/LoginView/index.js

Этот ПР - первый шаг к типизации компонентов.
Так как везде в коде используется только два пропа `onPress` и `icon` для кнопки, то именно их я и оставил. Остальное удалил, чтобы не плодить сложность.
Господа фронтенды, проверьте меня пожалуйста.

188 prop types

---

src/AppRouter.js
src/views/ProfileView/index.js

Вы согласны с тем что я написал в комментах в коде?

#342 update routes

---

.eslintrc
src/components/CommunityChoice/index.js
src/components/EventForm/EventForm.js
src/components/EventForm/helper.js
src/components/ServiceForm/ServiceForm.js
src/components/ServiceForm/helper.js

В этом пулреквесте реализовано сохранение communityId в базу данных при создании новой или изменении существующей записи: события или услуги.

#340 community choice

---

src/components/ButtonAction/index.js
src/components/ButtonExternalLink/index.js
src/components/ButtonLink/index.js
src/components/EventCard/index.js
src/components/EventForm/index.js
src/components/EventsFilter/index.js

Добавил propTypes компонентам, прошу оценить код

#188 prop types

---

src/components/CommunityList/communities.json

add community to community list

#352 add suzdals park

---

src/views/EventsView/index.js

fix #384
Add comment about first open events_view bug

[#384] FIrst open for EventsView

---

src/components/EventsFilter/index.js

fix #390 
Переименование кнопок фильтрации событий

fix(main screen) Rename calendar filter buttons

---

src/components/EventCard/index.js

fix #392 Скрываем в интерефейсе дату окончания для события

#392 - hide end time for event

---

src/components/EventCard/index.js

fix #392 Скрываем в интерфейсе дату если не указана

392 fix end event data 2

---

src/components/ServiceCard/ServiceCard.css
src/components/ServiceCard/index.js
src/views/ServicesView/ServicesView.css
src/views/ServicesView/index.js

Без картинок выглядит так:
Когда будут картинки, будет условно так:

#394 refactor ServiceCard

---

src/components/EventCard/index.js
src/utils/eventsLogic.js

decomposition function "getVerboseTime",
minor refactor component use new created function
Функция "getVerboseTime" разделена на части
Минорный рефактор компонента с использованием новых функций.

#396 refactor logic verbose user time

---

package.json
src/components/ServiceCard/index.js

#401 deleted react-add-to-calendar

---

package.json
src/views/LoadingView/index.js

#405 deleted  Dependencies unused

---

package.json
src/bootstrap.css
src/index.js

#407 deleted dependence  "bootstrap": "^4.1.3"

---

src/views/CommunitiesView/CommunitiesView.css
src/views/CommunitiesView/index.js
src/views/WelcomeView/index.js

New look: 
Теперь нам потребуются картинки сообществ с б**о**льшим разрешением, хотя бы 120х120.

#402 updated communities section on main page

---

src/components/EventCard/index.js
src/utils/eventsLogic.js

Добавил функцию опеределения года события отличного от текущего
Добавил в верстку карточки события блок с определением года.
add functioon checker another year in event
add block check to eventCard component

#403 add checker event another year

---

src/components/EventCard/index.js
src/utils/eventsLogic.js

Изменил место отображения года мероприятия -— теперь под датой
Поправил название переменной в верстке,
изменил тип возвращаемых данных функции на число

#403 fix event another year

---

src/components/EventCard/index.js
src/utils/eventsLogic.js

обновлен функционал возвращения даты из фукнции определения даты события
Удален лишний код в компонетах и файле с логикой
update function getVerboseDate - add another year logics
remove unwanted code from components

#416 Refactor another year events logic
